[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  command = "npm start"
  port = 3000
